#!/bin/sh

BOOKDIR="$HOME/Documents/Books/"
DIR="$BOOKDIR$(ls $BOOKDIR | sort | dmenu -r -i -p "Choose topic: ")" || exit 1
BOOKNAME=$(find "$DIR" -iname "$(find "$DIR" -iname "*.pdf" | rev | cut -d'/' -f1 | rev | sort | dmenu -i -l 10)")
zathura "$BOOKNAME" 2> /dev/null
